### ISSUE TITLE
Labels do not appear in c64debugger

### ISSUE THREAD

**Issue by retrosteve** [c64lib/asm-ka#2]
Using version 5.16, labels in the source code do not appear in c64debugger using the Ctrl+Shift+F5 view.  I rolled back to 5.13 and the labels did appear.

Issue appears to be introduced in the 5.14 kickass.jar.  Maybe this release note comment is related?

13/4-2020 : New release (v5.14):
Source locations added to debugdump file.

**Comment by maciejmalecki** [comment]
Sorry, but this is a mirror of the KickAss releases, and not the original KickAss repo. Official way to report errors to the KickAssembler is via Facebook group "retroassembler"
